window.SCHOOL_SEED = {
  users: [
    {
      id: "admin-demo",
      fullName: "Administrador",
      username: "admin",
      password: "1128467570",
      role: "admin",
      documentId: "",
      email: "",
      phone: "",
    },
    {
      id: "teacher-demo",
      fullName: "Docente",
      username: "docente",
      password: "Docente123!",
      role: "teacher",
      documentId: "",
      email: "",
      phone: "",
    },
    {
      id: "student-demo",
      fullName: "Estudiante",
      username: "estudiante",
      password: "Estudiante123!",
      role: "student",
      documentId: "",
      email: "",
      phone: "",
    },
  ],
  courses: [
    {
      id: "barberia",
      name: "Barbería",
      icon: "scissors",
      description: "Programa de barbería con clases teóricas, prácticas y brigadas.",
      lessons: [
        "Historia de la barbería: evolución y rol del barbero moderno.",
        "Bioseguridad: protocolos de esterilización, desinfección de herramientas y gestión de residuos.",
        "Ética y servicio al cliente: imagen profesional y comunicación efectiva.",
        "Tricología básica: estructura del cabello, cuero cabelludo y afecciones comunes.",
        "Morfología craneal: identificación de puntos óseos y protuberancias.",
        "Visajismo: estudio de las facciones para adaptar el corte según la forma del rostro.",
        "Herramientas de corte: uso y mantenimiento de clippers, trimmers y shavers.",
        "Herramientas manuales: manejo técnico de tijeras (filo dulce, microdentadas, de entresacar) y navaja.",
        "Postura ergonómica: prevención de lesiones profesionales.",
        "Fundamentos de particiones y secciones.",
        "Corte con tijera: técnicas de elevación, proyección y texturizado.",
        "Técnicas de degradado (fades): low fade, mid fade, high fade y skin fade.",
        "Taper fade y contornos (line-ups).",
        "Diseño de barba: adaptación según el crecimiento y la morfología facial.",
        "Técnicas de afeitado: preparación de la piel, uso de toallas calientes y manejo de la navaja.",
        "Barboterapia: cuidado de la piel y aplicación de productos post-afeitado.",
        "Teoría del color: círculo cromático y fondos de aclaración.",
        "Aplicación de tintes y matizadores.",
        "Técnicas modernas: platinados, high-lights y efectos de color.",
        "Manejo del secador y cepillos.",
        "Productos de fijación: pomadas, ceras, polvos de textura y lacas.",
        "Técnicas de peinado: pompadour, quiff, crop y estilos clásicos.",
        "Administración de la barbería: costos, inventarios y fijación de precios.",
        "Marketing digital: manejo de redes sociales y fotografía de trabajos.",
        "Emprendimiento: pasos para abrir un local propio.",
        "Sistemas de ondulación: técnicas de permanente y texturizado para crear volumen y movimiento (estilos curly).",
        "Alisados y relajación de rizos: aplicación técnica de productos para el control del volumen y reducción del encrespamiento.",
        "Química capilar: comprensión de los puentes de disulfuro y el pH de los productos químicos para garantizar la integridad de la hebra.",
        "Neutralización y post-tratamiento: protocolos para estabilizar el cabello tras procesos químicos intensos.",
        "Geometría del diseño: planificación de líneas, curvas y sombras en el cuero cabelludo.",
        "Manejo de herramientas de precisión: uso avanzado del trimmer y la navaja para trazados finos y realismo.",
        "Efectos de sombreado (shading): creación de dimensiones y profundidad mediante diferentes longitudes de cabello.",
        "Integración de diseño y corte: cómo combinar un diseño artístico con la estructura de un fade profesional.",
      ],
    },
    {
      id: "cejas-y-pestanas",
      name: "Cejas y Pestañas",
      icon: "image",
      description: "Temario de pestañas con visajismo, teoría y prácticas en cabezote y modelo real.",
      lessons: [
        "Presentación.",
        "Visajismo.",
        "Práctica de visajismo.",
        "Teoría.",
        "Clásica.",
        "Práctica cabezote 3D-4D.",
        "Práctica cabezote 5D-6D.",
        "Práctica cabezote pesta-húmedo.",
        "Práctica cabezote premium-híbrido.",
        "Wispy - volumen.",
        "Práctica modelo real YY.",
        "Práctica modelo real 3D.",
        "Práctica modelo real 4D.",
        "Práctica modelo real 5D.",
        "Práctica modelo real 6D.",
        "Práctica modelo real clásica.",
        "Práctica modelo real pestañina.",
        "Práctica modelo real premium.",
        "Práctica modelo real húmedo.",
        "Práctica modelo real híbrido.",
        "Práctica modelo real wispy.",
        "Práctica modelo real 8D.",
        "Práctica modelo real UYY.",
        "Práctica modelo real volumen.",
        "Práctica modelo real Foxy.",
        "Fibra café y examen final.",
      ],
    },
    {
      id: "estetica-facial-corporal",
      name: "Estética Facial y Corporal",
      icon: "award",
      description: "Programa integral de estética facial, corporal, depilación, masajes y emprendimiento.",
      lessons: [
        "Inducción al curso, presentación, perfil de la esteticista y ética profesional.",
        "Atención al cliente, presentación personal y responsabilidad profesional.",
        "Técnicas de estudio, organización del tiempo y hábitos de aprendizaje.",
        "Bioseguridad: normas, elementos de protección personal y prevención de riesgos.",
        "Bioseguridad: desinfección, esterilización y manejo de residuos. Evaluación y certificación en bioseguridad.",
        "Anatomía y fisiología básica de la piel. Tipos de piel.",
        "Diagnóstico facial y elaboración de historia clínica estética.",
        "Limpieza facial profunda: teoría y protocolo.",
        "Práctica de limpieza facial profunda.",
        "Hidratación, nutrición y protocolos según el tipo de piel.",
        "Introducción a la depilación. Tipos de cera, contraindicaciones y cuidados.",
        "Práctica de depilación facial y corporal.",
        "Masaje relajante corporal: teoría y práctica.",
        "Masaje reductor y reafirmante.",
        "Drenaje linfático manual.",
        "Moldeo corporal y protocolos combinados.",
        "Maquillaje profesional: preparación de la piel y visagismo.",
        "Maquillaje social y técnicas de corrección.",
        "Cuidados prequirúrgicos y postquirúrgicos: teoría.",
        "Protocolos y práctica de cuidados pre y postquirúrgicos.",
        "Servicios de spa: aromaterapia, relajación y experiencia del cliente.",
        "Prácticas saludables, bienestar integral y autocuidado.",
        "TIC aplicadas a la estética: redes sociales, fotografía y promoción de servicios.",
        "Emprendimiento: creación del negocio, atención al cliente, costos y estrategias de venta.",
        "Evaluación final teórica y práctica, retroalimentación y clausura del curso.",
      ],
    },
    {
      id: "maquillaje-profesional",
      name: "Maquillaje Profesional",
      icon: "palette",
      description: "Temario completo de maquillaje social, editorial, nupcial, fantasía y final teórico-práctico.",
      lessons: [
        "Historia del maquillaje. Ética y presentación profesional. Bioseguridad e higiene.",
        "Organización del kit de maquillaje. Conocimiento de herramientas y productos.",
        "Estudio de los tipos de rostro.",
        "Correcciones faciales.",
        "Diseño y armonía facial.",
        "Tipos de ojos, labios y cejas. Teoría del color aplicada al maquillaje.",
        "Tipos y estados de piel.",
        "Rutina de limpieza e hidratación. Uso de primers.",
        "Selección de bases y correctores. Técnicas de aplicación.",
        "Maquillaje de día.",
        "Maquillaje de noche.",
        "Maquillaje para eventos especiales.",
        "Aplicación de pestañas postizas. Iluminación y contorno.",
        "Técnicas de difuminado.",
        "Cut crease.",
        "Halo eye.",
        "Ojo de gato.",
        "Maquillaje para diferentes formas de ojos. Aplicación de pigmentos y glitter.",
        "Entrevista y asesoría a la clienta. Prueba de maquillaje.",
        "Técnicas de larga duración. Tendencias en maquillaje nupcial.",
        "Maquillaje para fotografía. Manejo de luces y cámaras.",
        "Maquillaje HD. Tendencias actuales.",
        "Colorimetría avanzada.",
        "Fantasía y caracterización básica. Uso de pedrería, escarcha y efectos especiales sencillos.",
        "Atención al cliente. Manejo de redes sociales. Fotografía de trabajos. Creación de marca personal. Costos y fijación de precios.",
        "Evaluación final: evaluación teórico-práctica. Desarrollo de un maquillaje profesional completo. Retroalimentación, recomendaciones y cierre del programa.",
      ],
    },
  ],
  enrollments: [
    { userId: "student-demo", courseId: "barberia" },
    { userId: "student-demo", courseId: "cejas-y-pestanas" },
    { userId: "student-demo", courseId: "estetica-facial-corporal" },
    { userId: "student-demo", courseId: "maquillaje-profesional" },
  ],
  assignments: [
    { userId: "teacher-demo", courseId: "barberia" },
    { userId: "teacher-demo", courseId: "cejas-y-pestanas" },
    { userId: "teacher-demo", courseId: "estetica-facial-corporal" },
    { userId: "teacher-demo", courseId: "maquillaje-profesional" },
  ],
  grades: [
    { courseId: "barberia", itemOrder: 1, studentId: "student-demo", notes: [{ label: "Clase", score: 4.8 }] },
    { courseId: "barberia", itemOrder: 2, studentId: "student-demo", notes: [{ label: "Clase", score: 4.6 }, { label: "Refuerzo", score: 4.4 }] },
    { courseId: "barberia", itemOrder: 12, studentId: "student-demo", notes: [{ label: "Práctica 1", score: 4.7 }, { label: "Práctica 2", score: 4.8 }, { label: "Práctica 3", score: 4.9 }] },
    { courseId: "cejas-y-pestanas", itemOrder: 1, studentId: "student-demo", notes: [{ label: "Clase", score: 4.9 }] },
    { courseId: "cejas-y-pestanas", itemOrder: 6, studentId: "student-demo", notes: [{ label: "Práctica 1", score: 4.7 }, { label: "Práctica 2", score: 4.8 }] },
    { courseId: "cejas-y-pestanas", itemOrder: 26, studentId: "student-demo", notes: [{ label: "Final", score: 4.9 }] },
    { courseId: "estetica-facial-corporal", itemOrder: 1, studentId: "student-demo", notes: [{ label: "Clase", score: 4.8 }] },
    { courseId: "estetica-facial-corporal", itemOrder: 8, studentId: "student-demo", notes: [{ label: "Clase", score: 4.5 }] },
    { courseId: "estetica-facial-corporal", itemOrder: 9, studentId: "student-demo", notes: [{ label: "Práctica 1", score: 4.9 }, { label: "Práctica 2", score: 4.8 }] },
    { courseId: "maquillaje-profesional", itemOrder: 1, studentId: "student-demo", notes: [{ label: "Clase", score: 4.7 }] },
    { courseId: "maquillaje-profesional", itemOrder: 10, studentId: "student-demo", notes: [{ label: "Clase", score: 4.6 }] },
    { courseId: "maquillaje-profesional", itemOrder: 13, studentId: "student-demo", notes: [{ label: "Práctica 1", score: 4.7 }, { label: "Práctica 2", score: 4.5 }] },
  ],
};
